### ISSUE TITLE
ReadME

### ISSUE THREAD

**Issue by Darkcast** [An0nUD4Y/Evilginx-Phishing-Infra-Setup#2]
could you please espesify the files one has to add or edit your instructions, its pretty vage for example 
Here you mention to remove these signature but you dont mention where is that in the souce or which files contain the code
Remove X-Gophish instances ( X-Gophish-Contact , X-Gophish-Signature)
could you update the read me with the files where I should change/remove these.

in this one 
Rewrite URLs on Phishing Pages to avoid detection through URL Path pattern matching (by Kuba). [This Feature not available in evilginx Public Version, You have to implement it yourself.]
but you dont give any directions on which file to add or where ?

thanks :)

**Comment by An0nUD4Y** [comment]
IOC’s codes changes with each version generally, So its not possible to include the modifications, Still you can find it here https://github.com/An0nUD4Y/Evilginx2-Phishlets?tab=readme-ov-file#evilginx3-easter-egg-patch-x-evilginx-header 

Also url rewrite is a evilginx pro feature, it would not be a good idea to release code snippet to modify public version to include that feature. Still i think it should not be difficult to do so.

**Comment by AnonyMousSKYsWORLD** [comment]
Please you can be kind to show where to implement it. I agree how unethical it is to release the feature at least be kind to give some direction or the line of code to implement this. Thanks, I am a fan of your content
